#!/bin/sh
GUNICORN=/home/std/consult-API/.venv/bin/gunicorn
ROOT=/home/std/consult-API/app
PID=/var/run/gunicorn-consult-API-flask.pid
PORT=5050

APP=app:app

if [-f $PID]; then rm $PID; fi

cd $ROOT exec $GUNICORN -w 1 -b localhost:$PORT --log-file=$ROOT/gunicorn.log --pid=$PID $APP